advanced:
  UA: Mozilla/5.0 (Linux; Android 7.1.2; V2284A Build/N2G47H; wv) AppleWebKit/537.36
    (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36 XWEB/1160253
    MMWEBSDK/20240301 MMWEBID/4107 MicroMessenger/8.0.48.2580(0x28003036) WeChat/arm64
    Weixin NetType/WIFI Language/zh_CN ABI/arm64 MiniProgramEnv/android
  baseUrl: tyxsjpt.seu.edu.cn
  miniappversion: minappv3.0.1
  plan_id: '403640124545491473'
  route_name: 桃园田径场
  route_rule: 九龙湖校区
  rule_id: '402186368309502988'
basic:
  calorie: '77'
  date: '2025-04-01'
  display_time: 00:08:00
  distance: '1.24'
  finish_image: C:/Users/Leo/Desktop/end.jpg
  finish_time: '18:08:00'
  seconds: '480'
  speed: 6'52''
  start_image: C:/Users/Leo/Desktop/start.jpg
  start_time: '18:00:00'
  student_id: '392522683303065115'
  tenant: NZJftK0pCDI4Ng==
  token: eyJ0eXAiOiJKc29uV2ViVG9rZW4iLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoi5p2O5p-D6ZSLIiwidG9rZW5fdHlwZSI6InRva2VuIiwidXNlcmlkIjoiMzkyNTIyNjgzMzAzMDY1MTE1IiwiYWNjb3VudCI6IjIxMzIzMzA4OSIsImV4cCI6MTc3NzA0NzA3NywibmJmIjoxNzQ1NTExMDc3fQ.6duxz7ri4z2GSgtxLQlMnVMb0Wemsc-K_4lvAaPks8A

